
package src.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-26T14:21:43.939+02:00
 * Generated source version: 3.3.4
 *
 */
public final class AracService_AracServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.service.vaadin.com/", "AracServiceImplService");

    private AracService_AracServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AracServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AracServiceImplService ss = new AracServiceImplService(wsdlURL, SERVICE_NAME);
        AracService port = ss.getAracServicePort();

        {
        System.out.println("Invoking saveArac...");
        src.service.AracDto _saveArac_arg0 = null;
        src.service.AracDto _saveArac__return = port.saveArac(_saveArac_arg0);
        System.out.println("saveArac.result=" + _saveArac__return);


        }
        {
        System.out.println("Invoking findAllArac...");
        java.util.List<src.service.AracDto> _findAllArac__return = port.findAllArac();
        System.out.println("findAllArac.result=" + _findAllArac__return);


        }

        System.exit(0);
    }

}
