package src.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-26T14:21:44.103+02:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "AracServiceImplService",
                  wsdlLocation = "file:/C:/Users/merve/IdeaProjects/Client-Uygulama/src/service/AracService.wsdl",
                  targetNamespace = "http://soap.service.vaadin.com/")
public class AracServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.service.vaadin.com/", "AracServiceImplService");
    public final static QName AracServicePort = new QName("http://soap.service.vaadin.com/", "AracServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/merve/IdeaProjects/Client-Uygulama/src/service/AracService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AracServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/merve/IdeaProjects/Client-Uygulama/src/service/AracService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AracServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AracServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AracServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AracServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AracServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AracServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AracService
     */
    @WebEndpoint(name = "AracServicePort")
    public AracService getAracServicePort() {
        return super.getPort(AracServicePort, AracService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AracService
     */
    @WebEndpoint(name = "AracServicePort")
    public AracService getAracServicePort(WebServiceFeature... features) {
        return super.getPort(AracServicePort, AracService.class, features);
    }

}
