package src.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-26T14:21:44.077+02:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://soap.service.vaadin.com/", name = "AracService")
@XmlSeeAlso({ObjectFactory.class})
public interface AracService {

    @WebMethod
    @Action(input = "http://soap.service.vaadin.com/AracService/saveAracRequest", output = "http://soap.service.vaadin.com/AracService/saveAracResponse")
    @RequestWrapper(localName = "saveArac", targetNamespace = "http://soap.service.vaadin.com/", className = "src.service.SaveArac")
    @ResponseWrapper(localName = "saveAracResponse", targetNamespace = "http://soap.service.vaadin.com/", className = "src.service.SaveAracResponse")
    @WebResult(name = "return", targetNamespace = "")
    public src.service.AracDto saveArac(

        @WebParam(name = "arg0", targetNamespace = "")
        src.service.AracDto arg0
    );

    @WebMethod
    @Action(input = "http://soap.service.vaadin.com/AracService/findAllAracRequest", output = "http://soap.service.vaadin.com/AracService/findAllAracResponse")
    @RequestWrapper(localName = "findAllArac", targetNamespace = "http://soap.service.vaadin.com/", className = "src.service.FindAllArac")
    @ResponseWrapper(localName = "findAllAracResponse", targetNamespace = "http://soap.service.vaadin.com/", className = "src.service.FindAllAracResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<src.service.AracDto> findAllArac()
;
}
